### ISSUE TITLE
Error when attempting to export to c

### ISSUE THREAD

**Issue by XKoop7321** [wRadion/RM2ExCoop#1]
The error I get looks like this:

KeyNotFoundException:
	The given key '32' was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RM2ExCoop.RM2C.Level..ctor(Int32 id)
   at RM2ExCoop.RM2C.Script..ctor(Int32 level)
   at RM2ExCoop.RM2C.Rom.ExportLevel(Int32 levelId, StreamWriter lvldefs, Options options, List`1 allWaterBoxes, List`1 m64Files, List`1 seqNums)
   at RM2ExCoop.RM2C.Main.Run(String romPath, Options options)
   at RM2ExCoop.MainWindow.<>c__DisplayClass2_0.<RM2CBtn_Click>b__0()

I don't know how to fix it, I also have a problem where it won't export all of the levels for exporting to EXCOOP. It only does Big Boos Haunt.

**Comment by XKoop7321** [comment]
Can someone help me?

**Comment by ElephatGayMamario** [comment]
i think its because it tries to import level id 32 but since theres no level id 32 that happens
